version: "3.9"

services:
  app:
    container_name: frontend
    build: .
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    stdin_open: true
    command: npm start
